swagger: '2.0'
info:
  title: KTApiProxy
  x-ibm-name: ktapiproxy
  version: 1.0.0
schemes:
  - https
basePath: /ktapiproxy
security:
  - {}
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientID:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
x-ibm-configuration:
  phase: realized
  testable: true
  enforced: true
  properties:
    target-url:
      value: 'https://apim-services.mybluemix.net/banka/v1/branches'
      description: The URL of the target service for bank response
      encoded: false
    target-url2:
      value: 'https://randomuser.me/api'
  catalogs: {}
  cors:
    enabled: true
  application-authentication:
    certificate: false
  assembly:
    execute:
      - switch:
          version: 2.0.0
          title: switch
          case:
            - condition: (($operationID() = 'getBranches'))
              execute:
                - invoke:
                    title: invoke
                    version: 2.0.0
                    verb: keep
                    target-url: $(target-url)
                    header-control:
                      type: blacklist
                      values: []
                    parameter-control:
                      type: blacklist
                      values: []
                    username: sourchak
                    password: 'hnkapic#4u'
            - condition: (($operationID() = 'getRandom'))
              execute:
                - invoke:
                    title: invoke
                    version: 2.0.0
                    verb: keep
                    target-url: $(target-url2)
                    header-control:
                      type: blacklist
                      values: []
                    parameter-control:
                      type: blacklist
                      values: []
                    username: sourchak
                    password: 'hnkapic#4u'
  gateway: datapower-api-gateway
paths:
  /kTApiProxy2:
    get:
      operationId: getRandom
      responses:
        '200':
          description: success
          schema:
            type: object
      consumes: []
      produces: []
  /kTApiProxy:
    get:
      operationId: getBranches
      responses:
        '200':
          description: success
          schema:
            type: object
      consumes: []
      produces: []
